/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controladores.FabricaControl;
import Controladores.IFachadaControl;
import Entidades.Clientes;
import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author ferra
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    PanelPedidos pedidos;
    PanelServiciosEntregables serviciosEntregables;
    IFachadaControl fachadaControl;
    Clientes cliente;
    int row;
    int num = 0;

    public FrmPrincipal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        fachadaControl = FabricaControl.getFachadaDeControl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        menuPedidos = new javax.swing.JButton();
        botonEntregablesServicios = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        panelPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(131, 19, 43));

        jPanel1.setBackground(new java.awt.Color(73, 0, 10));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sage/logo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic Medium", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Adriana Felix");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        menuPedidos.setBackground(new java.awt.Color(57, 0, 10));
        menuPedidos.setFont(new java.awt.Font("Yu Gothic Medium", 0, 24)); // NOI18N
        menuPedidos.setForeground(new java.awt.Color(255, 255, 255));
        menuPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sage/pedidos.png"))); // NOI18N
        menuPedidos.setText("      Pedidos");
        menuPedidos.setActionCommand("Paquetes");
        menuPedidos.setBorder(null);
        menuPedidos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPedidosActionPerformed(evt);
            }
        });
        jPanel1.add(menuPedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 290, 120));

        botonEntregablesServicios.setBackground(new java.awt.Color(57, 0, 10));
        botonEntregablesServicios.setFont(new java.awt.Font("Yu Gothic Medium", 0, 24)); // NOI18N
        botonEntregablesServicios.setForeground(new java.awt.Color(255, 255, 255));
        botonEntregablesServicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sage/paquetes.png"))); // NOI18N
        botonEntregablesServicios.setText("    Paquetes");
        botonEntregablesServicios.setActionCommand("Paquetes");
        botonEntregablesServicios.setBorder(null);
        botonEntregablesServicios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonEntregablesServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEntregablesServiciosActionPerformed(evt);
            }
        });
        jPanel1.add(botonEntregablesServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 290, 120));

        jButton6.setBackground(new java.awt.Color(57, 0, 10));
        jButton6.setFont(new java.awt.Font("Yu Gothic Medium", 0, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sage/reportes.png"))); // NOI18N
        jButton6.setText("    Reportes");
        jButton6.setActionCommand("Paquetes");
        jButton6.setBorder(null);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 730, 290, 120));

        jButton7.setBackground(new java.awt.Color(57, 0, 10));
        jButton7.setFont(new java.awt.Font("Yu Gothic Medium", 0, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sage/clientes.png"))); // NOI18N
        jButton7.setText("     Clientes");
        jButton7.setActionCommand("Paquetes");
        jButton7.setBorder(null);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 290, 120));

        jButton8.setBackground(new java.awt.Color(57, 0, 10));
        jButton8.setFont(new java.awt.Font("Yu Gothic Medium", 0, 24)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sage/agenda2.png"))); // NOI18N
        jButton8.setText("    Actividades");
        jButton8.setActionCommand("Paquetes");
        jButton8.setBorder(null);
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 290, 120));

        jPanel3.setBackground(new java.awt.Color(131, 19, 43));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1253, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 135, Short.MAX_VALUE)
        );

        panelPrincipal.setBackground(new java.awt.Color(107, 19, 43));
        panelPrincipal.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 971, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPedidosActionPerformed
        // TODO add your handling code here:
        panelPrincipal.removeAll();
        pedidos = new PanelPedidos(fachadaControl,panelPrincipal);
        panelPrincipal.repaint();
        panelPrincipal.revalidate();
        panelPrincipal.add(pedidos, "Pedidos");
    }//GEN-LAST:event_menuPedidosActionPerformed

    private void botonEntregablesServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEntregablesServiciosActionPerformed
        // TODO add your handling code here:
        panelPrincipal.removeAll();
        serviciosEntregables = new PanelServiciosEntregables(fachadaControl,panelPrincipal);
        panelPrincipal.repaint();
        panelPrincipal.revalidate();
        panelPrincipal.add(serviciosEntregables, "Servicios y Entregables");
    }//GEN-LAST:event_botonEntregablesServiciosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEntregablesServicios;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton menuPedidos;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
